### ISSUE TITLE
[Bug] Missing `custom_branch_only` from retrieved dbt Cloud job config

### ISSUE THREAD

**Issue by lewisarmistead** [dbt-labs/dbt-jobs-as-code#59]
**Describe the bug**
`custom_branch_only` config is missing from the job definitions retrieved from our dbt Cloud instance.

**To Reproduce**
When running any of the CLI commands from `dbt-jobs-as-code` other than `validate`, the following error is encountered:
```
pydantic.error_wrappers.ValidationError: 1 validation error for JobDefinition
triggers -> custom_branch_only
  field required (type=value_error.missing)
```
Example of failing command: `poetry run dbt-jobs-as-code import-jobs --account-id XXXX` or `poetry run python src/main.py import-jobs --account-id XXXX`

From a debugging session, I put a breakpoint at [`src/client/__init__.py:139`](https://github.com/dbt-labs/dbt-jobs-as-code/blob/c7f0027b48e831ec78e023cb515abfbd3ddef3ac/src/client/__init__.py#L139) - the instantiation of the `JobDefinition` class on that line is throwing validation errors because of the missing `triggers -> custom_branch_only` fields. Printing the triggers from all jobs within the debugging session shows that the `custom_branch_only` field isn't present for any of our jobs:
```py
[job.get('triggers') for job in jobs]
```
which returns the following (truncated):
```
[{'git_provider_webhook': False, 'github_webhook': False, 'schedule': True},
 {'git_provider_webhook': False, 'github_webhook': False, 'schedule': True},
 {'git_provider_webhook': False, 'github_webhook': False, 'schedule': False},
...
]
```

**Expected behavior**
Imported job definitions contain the `triggers -> custom_branch_only` field and avoid validation errors when building list of `JobDefinition` classes

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - dbt Core Version: 1.6
 - `dbt-jobs-as-code` Version: 0.2.0

**Additional context**
This may be an issue with the dbt Cloud API or an issue with our dbt Cloud account - when running an API request to our jobs endpoint directly (I used Postman), I'm seeing that none of our jobs have the `custom_branch_only` field present.

We've been using `dbt-jobs-as-code` within our CI/CD process for about a month now and have the `custom_branch_only` field present within all of our job definitions, which we retrieved originally using `import-jobs` and was working until yesterday. We noticed the issue when a PR was opened yesterday and our GitHub action we use to show planned job changes failed - note: we encounter the error above with both v0.1.0 and v0.2.0 of `dbt-jobs-as-code`

**Comment by b-per** [comment]
This should be fixed in 0.2.1 now! Let me know if this is not the case.

**Comment by lewisarmistead** [comment]
@b-per - thanks for addressing this so quickly! We're running into the issue now where our planned dbt Cloud job changes are showing diffs due to the `custom_branch_only` fields for all our jobs:
```
Jobs are different - Diff: {'values_changed': {"root['triggers']['custom_branch_only']": {'new_value': True, 'old_value': False}}}
```
If I'm understanding the fix correctly, if no `custom_branch_only` field is retrieved from the dbt Cloud API for a job, it assumes it's set to True, so the output of `plan` is showing that it will be set to False for our jobs for which we've explicitly set this field to False. 

This isn't a huge deal, but since we're not using custom branches on any of our jobs that we've defined in our job config YML, our planned changes will show this diff until we start receiving actual the `custom_branch_only` config from the API for our jobs. I think it would be better default behavior if the `custom_branch_only` were assumed to be False since that's the default setting when setting up a job via the dbt Cloud UI, and I assume it would show fewer changes for others if they're encountering similar issues that we are - I can open a PR reflecting that suggestion while I try to figure out why we're not receiving the `custom_branch_only` fields for our jobs from the dbt Cloud API, but let me know if you have suggestions in the meantime.

**Comment by b-per** [comment]
Thanks. I'm ok with it. I will merge the PR and get another release out.
