### ISSUE TITLE
[Feature] seperate environment management

### ISSUE THREAD

**Issue by chenxuanrong** [dbt-labs/dbt-jobs-as-code#64]
**Describe the feature**

Hi team, I'm wondering if there's plan on supporting multi environment management.
i.e. files to target uat, staging and production deployment individually while not affecting each other.

The current feature seems require users to put all jobs definitions under one yaml file. 
It would be really useful to bound the plan and sync process within a environment.

**Describe alternatives you've considered**

**Who will this benefit?**

Users will be able to deploy to seperate environments based on stages the PR.

**Additional context**

The screenshot illustrates an individual `prd.yml` that contains all production jobs will try to delete staging jobs.

<img width="1537" alt="image" src="https://github.com/dbt-labs/dbt-jobs-as-code/assets/90671468/3810a5e9-825d-4a6c-bf14-46a48d192fc5">

**Are you interested in contributing this feature?**
Keen to contribute

**Comment by b-per** [comment]
Hi @chenxuanrong 

Sorry that we didn't reply before!

Yes, actually, we are working on adding `--project-id` and `--environment-id` as filters for `sync` and `plan`.

This should allow people to use this tool for job "promotion" between environments and projects.

**Comment by mani-dbt** [comment]
@chenxuanrong — With the latest version of dbt-jobs-as-code (0.6.0), you can use templating and provide project/environment details as an argument to plan and sync commands (using vars-yml). Please check it out.
