### ISSUE TITLE
[BUG] Error 400: Invalid Request Due to Unexpected Property custom_branch_only

### ISSUE THREAD

**Issue by sedukulla** [dbt-labs/dbt-jobs-as-code#91]
I encountered an error when adding a new job or updating an existing job in the dbt-jobs-as-code process. The issue arises from the presence of the custom_branch_only field within the triggers configuration. The system responds with a 400 error, indicating that this property is not allowed.

```shell
| ERROR    | src.client:create_job:110 - {'status': {'code': 400, 'is_success': False, 'user_message': 'The request was invalid. Please double check the provided data and try again.', 'developer_message': ''}, 'data': {'triggers': "Additional properties are not allowed ('custom_branch_only' was unexpected)"}, 'extra': {}, 'error_code': None}
```

### Current Configuration:
Here is an example of the triggers configuration causing the issue:

```shell
triggers:
  github_webhook: false
  git_provider_webhook: false
  custom_branch_only: true  # This field is not supported and triggers the error
  schedule: false
  on_merge: false
```

**Comment by il-dat** [comment]
Up please 🆙

**Comment by b-per** [comment]
Can you just remove the `custom_branch_only` config and try again?

The field was deprecated/optional for some time now, but it might be that it is now raising errors.

**Comment by il-dat** [comment]
> Can you just remove the `custom_branch_only` config and try again?
> 
> The field was deprecated/optional for some time now, but it might be that it is now raising errors.

Unfortunately, it doesn't work still.

I think this config is implicitly passed in the POST request with value = False if not specified

**Comment by b-per** [comment]
Oh, OK. Let me have a look then.

**Comment by b-per** [comment]
I am just pushing a PyPi release called `0.8.1` with a fix.

I think that the team might also be looking at making `custom_branch_only` being accepted but ignored. And in that case, previous version of dbt-jobs-as-code would continue working.
