### ISSUE TITLE
[Bug] incompatibility of importlib-metadata

### ISSUE THREAD

**Issue by rsong24** [dbt-labs/dbt-jobs-as-code#93]
**Describe the bug**
`dbt-core` has requirement of `dbt-semantic-interfaces` [>=0.7.1,<0.8](https://github.com/dbt-labs/dbt-core/blob/8fe5ea1ee7640da2ec93a4deff26b845779d2ed5/core/setup.py#L72), and it in turn requires `importlib-metadata` to be [">=6.0,<7"](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/a80b2556f796d746d1b850cb97a911db6cd53aec/pyproject.toml#L32), however, `dbt-jobs-as-code` requires `importlib-metadata` to be ["^7.2.0"](https://github.com/dbt-labs/dbt-jobs-as-code/blob/cf401e2bed67b922041f51f3406c73e8a4e93195/pyproject.toml#L25C22-L25C30), this requirement has been added since 0.6.0

**To Reproduce**
1. create a pipfile
2. under packages, add dbt-jobs-as-code = "0.8.1" and dbt-core = ">1.8.0,1.9.0"
3. run `pipenv lock --verbose`

**Expected behavior**
verions have conflicting dependencies will be reported

**Screenshots**
<img width="1462" alt="Screenshot 2024-09-18 at 1 47 28 PM" src="https://github.com/user-attachments/assets/694def99-b552-4d6d-90b2-14a4457a17f9">

**Desktop (please complete the following information):**
 - OS [e.g. iOS]:
 - dbt Core Version [1.8.6]:
 - `dbt-jobs-as-code` Version [0.8.1]:

**Comment by b-per** [comment]
Updated in 0.8.2 !
